### ISSUE TITLE
Make keyboard shortcut configurable

### ISSUE THREAD

**Issue by SamHH** [lusakasa/saka#1]
Hi there,

I currently have all of my *x* + space keyboard combos taken up outside of Chrome (Terminal, Spotlight, etc). I'd like to be able to configure the keyboard shortcut.

Thanks!

**Comment by eejdoowad** [comment]
To configure your keyboard shortcuts and make others available globally, enter "chrome://extensions/configureCommands" in your URL bar and hit enter.

Hopefully that'll suffice

Thanks!

**Comment by SamHH** [comment]
That works, thanks!
