### ISSUE TITLE
Select next option by default

### ISSUE THREAD

**Issue by cwagner22** [lusakasa/saka#10]
It would be awesome if Saka could select the next site when the popup opens. (like in intellij/webstorm) So if I want to go back to the previous site quickly I just have to toggle Saka and press Enter instead of having to move down to the 2nd option.

Also really looking to be able to set a custom hotkey on Firefox. Maybe Ctrl/Cmd+E or Ctrl/Cmd+Shift+O should be the default.

Thanks.

**Comment by pureooze** [comment]
@eejdoowad @cwagner22 This change seems pretty simple, thoughts?

https://github.com/pureooze/saka/commit/35b039658da261c36094bf066847203855d6dbb5

**Comment by cwagner22** [comment]
Yeah that'd probably be fine although I didn't dig in the code too much. But you should probably set it to 0 if there is only one webpage open (= one suggestion). 
I hope this project is still maintained, it looks promising...

**Comment by pureooze** [comment]
Good point, fixed that

**Comment by pureooze** [comment]
This should now be working as expected in the master branch, fixed in https://github.com/lusakasa/saka/pull/13

**Comment by pureooze** [comment]
@cwagner22 this has been released on chrome, will do firefox soon.

**Comment by pureooze** [comment]
Released it for firefox too.
