### ISSUE TITLE
Non-arrow shortcuts for selecting previous/next item in the list?

### ISSUE THREAD

**Issue by aldanor** [lusakasa/saka#11]
Wonder if it would make sense to have some shortcuts for navigating the list of choices? (ideally somewhere on the home row and involving up/down arrow keys) -- for example `Ctrl-J` and `Ctrl-K`?

Thanks!

**Comment by pureooze** [comment]
@aldanor this should be doable, I am going to add it to the 0.16.2 release milestones.
