### ISSUE TITLE
Saka needs a Maintainer

### ISSUE THREAD

**Issue by eejdoowad** [lusakasa/saka#12]
I started writing Saka when my life was much less busy. Lately, my job and a different project consume the bulk of my time and energy. As a result, development of Saka has stalled and issues go unanswered.

I'm looking for someone who's willing to step up and lead this project. If you're interested, please email me at eejdoowad@gmail.com.

**Comment by pureooze** [comment]
@eejdoowad I have emailed you about this

**Comment by eejdoowad** [comment]
I can't find your email. Can you resend it? thanks

**Comment by pureooze** [comment]
@eejdoowad sent it again

**Comment by eejdoowad** [comment]
@pureooze is the new maintainer of Saka. Thank you!
