### ISSUE TITLE
Open source Saka

### ISSUE THREAD

**Issue by bonds** [lusakasa/saka#3]
Do you plan to release the source for Saka? I just discovered Saka Key and tried out Saka and they are both nice, but Saka is closed source. I prefer building my workflow/habits around open source tools, so I won't be using Saka for now. If you plan to open source it, perhaps say so and leave this ticket open. If not close, and I can stay subscribed on the off chance you change your mind down the road, I'll be notified. :)

**Comment by eejdoowad** [comment]
Hi bonds, I don't currently intend to release Saka's source code, but it's not something I'll completely rule out. My plan is to make a browsing assistant so good, people would pay money to use it. Open source software is, unfortunately, more difficult to monetize.

I'm working on other projects in parallel, and depending on how they work out, I may decide to open up Saka. I'd also be enticed to open source Saka if more people contributed to Saka Key and expressed interest in improving Saka.

Until then, I understand your hesitance to use closed source software. I'll post an update here if/when I change my mind. Thanks.

**Comment by bonds** [comment]
Got it, thanks for the explanation.

**Comment by DamienCassou** [comment]
I agree with @bonds that I refrain from using closed-source programs. I would love to use Saka, but not at the cost of introducing a closed source browser extension. I could however participate to a donation campaign whose goal is to make the project FLOSS.

**Comment by eejdoowad** [comment]
Done. Saka is now open source and rearchitected to support Firefox. Install at https://addons.mozilla.org/en-US/firefox/addon/saka/.

I have too many projects and not enough time, and I don't want the project to stagnate.

**Comment by DamienCassou** [comment]
Sufyan Dawoodjee <notifications@github.com> writes:

> Done. Saka is now open source and rearchitected to support
> Firefox. Install at
> https://addons.mozilla.org/en-US/firefox/addon/saka/.
>
> I have too many projects and not enough time, and I don't want the
> project to stagnate.

Thank you very much. You probably want do give some love to all of your
projects but your day is only 24 hours long. You sometimes have to make
hard decisions. That's hard.

Merging saka and saka key could help you a bit too.

Thanks again

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by alexherbo2** [comment]
Really awesome.
