### ISSUE TITLE
What is the keyboard shortcut to open ?

### ISSUE THREAD

**Issue by magick93** [lusakasa/saka#4]
Hello

I cannot find on your website or in the readme what the keyboard shortcut is to pen Saka.
Would be good if this was made clear.

Thanks

**Comment by eejdoowad** [comment]
Sorry, it's CTRL+SPACE on Linux/Windows or ALT+SPACE on Mac. It should have been listed on the page where you installed the extension. I just released the first version that works properly on Firefox, if that's your browser. You can also click the Saka Icon in the toolbar.
