### ISSUE TITLE
Option to change default mode

### ISSUE THREAD

**Issue by tkim90** [lusakasa/saka#47]
First of all, thank you for creating such an amazing extension. 

Feature request to add an option to define the default 'search mode'. Currently it searches for current open tabs, but I am much more likely to open a new tab from my bookmarks.

- Add option for default search mode. Ex. If I change it to "Bookmarks", summoning Saka will set the search for my bookmarks instead of the current open tabs.

**Comment by pureooze** [comment]
Thanks for filing an issue! I think this feature already exists. If you check the options page you can change what the default mode is.
![image](https://user-images.githubusercontent.com/2337524/41943667-49e38d74-7972-11e8-8bdd-a1be4cd8e08f.png)

**Comment by pureooze** [comment]
No problem! Feel free to make issues in the future for any features you wish to see added (or even removed) from Saka. I try and check back here every day.
