### ISSUE TITLE
Feature Request: Trigger With Hotkey

### ISSUE THREAD

**Issue by drwicked** [lusakasa/saka#5]
I'm not sure if it's possible to map opening a Chrome extension to a hotkey but it would be awesome to be able to open the overlay with a hotkey for a more spotlight-like workflow.

Thanks!

**Comment by eejdoowad** [comment]
CTRL+SPACE or ALT+SPACE on macs should have you covered. Instructions are on the install page, but it looks like I have to make it more obvious.

**Comment by drwicked** [comment]
Ahh, I have alt-space mapped to Alfred, that's why it didn't work. Maybe the option to remap? I'd like to use Cmd+P or similar to bring it into parity with sublimetext. Thanks for the response!

Dr.W

**Comment by eejdoowad** [comment]
If you’re on chrome, you can select Custom keybinding. See the instructions on the chrome web store page. There’s no way to change the keybinding on Firefox unfortunately.

**Comment by eejdoowad** [comment]
Also, the next release of Saka Key will let you assign any key to opening Saka on Firefox. This is already supported on Chrome.
