### ISSUE TITLE
Not able to find url that has "abc"

### ISSUE THREAD

**Issue by orschiro** [lusakasa/saka#54]
What a great extension, love it!

Could you help me understand why it doesn't find the page shown below?

Could it be because I suspended the tab?

How would I have to search to find this tab?

Thank you!

![image](https://user-images.githubusercontent.com/170947/42407922-ab316a6a-81c4-11e8-8b7d-84809f164dd9.png)

![screenshot from 2018-07-07 07-40-40](https://user-images.githubusercontent.com/170947/42407281-57c0ea8c-81b9-11e8-85bf-19ea60a84669.png)

**Comment by pureooze** [comment]
Hi @orschiro thanks for making an issue. I just tried using the great suspender extension and suspending http://radio.abc.net.au/ manually by going to the tab and clicking suspend in the extension menu. It seems to work fine for me, I see an entry in Saka for the suspended tab.

![image](https://user-images.githubusercontent.com/2337524/42412301-c4fb5376-81d7-11e8-9378-a83d1b888f5c.png)

I thought the issue might be that you were relying on the auto suspend feature so the tab wasnt getting picked up but when I try using the "suspend other tabs" feature, the tabs I had open are still visible in the saka search.

Could you provide step by step instructions on how to reliably reproduce this?

**Comment by orschiro** [comment]
I appreciate your help, Uzair!

Here are my steps:

1. Go to http://radio.abc.net.au/programitem/pexQXaaRBL?play=true
2. Suspend manually using the Great Suspender
3. Go to another tab
4. Launch Saka
5. Type abc

Doing this, gives me:

[image: image.png]

**Comment by pureooze** [comment]
Isn't the last result in that image the tab you were looking for? When I follow the steps you mentioned, the tab shows up as a result at the very bottom of page 1 for me. If that is the case I think the issue with the missing result may just have to do with the Fuse.js threshold being too strict.

**Comment by orschiro** [comment]
> If that is the case I think the issue with the missing result may just
have to do with the Fuse.js threshold being too strict.

I think you are correct! Is there any way we can make it less strict?

**Comment by pureooze** [comment]
I messed around with Fuse a bit and it seems like this cant be changed by just modifying the threshold or distance settings. When I modify those the desired result just disappears from the results altogether. I was able to get better results when enabling 'Tokenize' and 'Match all tokens'. I'll look more into this and update how saka does Fuzzy search if I find this makes more sense for users.

**Comment by orschiro** [comment]
@pureooze I appreciate your further tests and I remain confident that you will find a solution that benefits all users equally. Appreciated!

**Comment by pureooze** [comment]
@orschiro I think I have got this fixed by just increasing the distance that Fuse uses when performing a search so it doesn't punish titles/urls that are longer than their peers.

![image](https://user-images.githubusercontent.com/2337524/44694359-f4ff5780-aa3a-11e8-95dd-3abef434b87c.png)

PR coming soon.

**Comment by orschiro** [comment]
@pureooze thanks so much for your work on this issue!

This is looking very good. :-)
