### ISSUE TITLE
Use separate manifest files for Firefox and Chrome

### ISSUE THREAD

**Issue by pureooze** [lusakasa/saka#56]
Saka should have separate manifest files that are chosen when the build command is run. Ideally we have one main manifest and then two smaller manifests that contain browser specific settings. We could then use Webpack to combine the main manifest with the browser specific one and then place it in the dist directory.

**Comment by pureooze** [comment]
ping @DevVex ^^

**Comment by eejdoowad** [comment]
https://github.com/lusakasa/saka-key/blob/master/webpack.config.js

https://github.com/lusakasa/saka-key/manifest
