### ISSUE TITLE
Allow for custom keyboard shortcut

### ISSUE THREAD

**Issue by tnguyen14** [lusakasa/saka#7]
Is it possible to activate this extension using a different keyboard shortcut from Ctrl-Space? That one is already been mapped on my machine for an omnisearch box on the computer.

**Comment by alexherbo2** [comment]
Yep, the [commands][Commands] API allows that.

Go on `chrome://extensions/configureCommands` to configure the keyboard shortcuts for extensions and applications.

[Commands]: https://developer.chrome.com/apps/commands

**Comment by tnguyen14** [comment]
I am using Firefox 57. Is that available there as well?

**Comment by alexherbo2** [comment]
They have a [commands][firefox.commands] API too – which based on [Chromium’s one][chrome.commands] – but I’ve not found how.

[firefox.commands]: https://developer.mozilla.org/Add-ons/WebExtensions/API/commands
[chrome.commands]: https://developer.chrome.com/extensions/commands

**Comment by eejdoowad** [comment]
Firefox's current state of affairs is confusing. The commands API exists, but only the first keybinding in the manifest file is respected and there's no way for users to configure keybindings. Maybe CMD+E should be the default keybinding on Macs since many users already have ALT+SPACE mapped to something else.  The next release of Saka Key will let you configure any key to open Saka on Firefox.

**Comment by tnguyen14** [comment]
Thanks @eejdoowad. Do you know when that release would be?

**Comment by tnguyen14** [comment]
And I agree that it should be "Cmd+e" on Mac, and "Ctrl+e" on Windows as well.

**Comment by eejdoowad** [comment]
As soon as I resolve the issue that corrupts your setting when Saka Key updates on Firefox.

**Comment by baybatu** [comment]
hi, is there any update on making shortcut cmd+e on Firefox?

**Comment by pureooze** [comment]
@baybatu this should already work, its set in the manifest:

https://github.com/lusakasa/saka/blob/master/static/manifest.json#L15-L40

**Comment by chrise86** [comment]
It does look like `command + e` should work by looking at `src/background_page/index.js`, any reason why it wouldn't work?

**Comment by pureooze** [comment]
> It does look like `command + e` should work by looking at `src/background_page/index.js`, any reason why it wouldn't work?

Looks like it is fine in chrome but firefox does not seem to work with that hotkey. I will have to look into this, this should work 🤔

**Comment by pureooze** [comment]
I think Command+E is conflicting with some browser/global hotkey. It seems to work if it gets changed to MacCtrl. I'm not sure why Firefox is not respecting the Ctrl -> Command key mapping.

**Comment by pureooze** [comment]
<img width="1045" alt="Screen Shot 2019-05-16 at 3 50 12 AM" src="https://user-images.githubusercontent.com/2337524/57836037-dfc78600-778d-11e9-9738-5a93459ff1ae.png">

Firefox now allows you to customize hotkeys for extensions by selecting "Manage Extension Shortcuts" on the about:addons page. Chrome has allowed this for a while.

Closing this issue as you should now be able to use whatever hotkeys work best on your system.
