### ISSUE TITLE
FeatureRequest: Close selected tab

### ISSUE THREAD

**Issue by pigeonlips** [lusakasa/saka#86]
I'm a huge fan of using the keyboard, so let me say this is a great extension ! 

I'd love a keybinding for closing the currently selected tab in the drop down of saka. Not sure how hard that would be to implement. 

**I guess my use case is this :** 
I often use saka to review what tabs i currently have open and close those i'm finished with. So I open saka search for tabs and arrow down to a tab I want to close. Open/switch to it.  Close it with ctrl-w. Reopen saka, repeat the process.

If saka had a key binding to close the currently selected (in saka) tab i could open saka, select/search for the tab press a key to close  Ideally saka will retain focus so i can close another tab, and another, etc.

Just a thought. Thanks for the great extension.

**Comment by pureooze** [comment]
This seems pretty easy to implement. Saka maintains a list of the tabs with their ID so simply calling the tabs.remove API with the desired ID would be sufficient to implement this.

**API reference:** https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/remove

**Comment by pureooze** [comment]
@pigeonlips This feature has been released in the latest version of Saka (0.17.1)

**Comment by pigeonlips** [comment]
Thanks Heaps. Look forward to using it !
