### ISSUE TITLE
Doesn't work in Firefox 57 (macOS)?

### ISSUE THREAD

**Issue by fuyu** [lusakasa/saka#9]
Hello, thank you for the very good job on saka extensions.
Probably I'm missing something obvious but I can't make Saka work in FF57. I have these versions:
- Saka Key 1.25.2
- Saka 0.12.0

I've mapped Saka for Ctrol+O. I also noticed that in Saka Key options it still says "Coming to Firefox soon" which makes me think Saka Key doesn't know that there is Saka on Firefox now?

<img width="560" alt="screen shot 2017-11-20 at 14 07 19" src="https://user-images.githubusercontent.com/1557716/33017809-766bb9a6-cdfc-11e7-9e63-aa244fd4ff48.png">

**Comment by eejdoowad** [comment]
I haven't yet made a release that integrates the two extensions on Firefox. It'll be in the next release. CTL+SPACE is the current default keybinding.

**Comment by fuyu** [comment]
Awesome! I had iTerm2 mapped to Option+Space so it was stealing the keystroke event.

**Comment by cwagner22** [comment]
Any update?

**Comment by pureooze** [comment]
@fuyu is this still an issue?

**Comment by fuyu** [comment]
Yes, my custom bindings still don't trigger Saka to appear.

**Comment by pureooze** [comment]
This issue should be fixed once the two PRs above are merged. There is a change that has to be made in Saka Key so that it uses a different extension ID when in Firefox vs. Chrome. There is also a change in Saka to use the `browser.*` API instead of the `chrome.*` APIs.

**Comment by pureooze** [comment]
I release 0.16.1 to Firefox and Chrome so this should work on both browsers once https://github.com/lusakasa/saka-key/pull/209 is released. 💯🎉🍾
