### ISSUE TITLE
Show pinned tab status?

### ISSUE THREAD

**Issue by orschiro** [lusakasa/saka#90]
Dear @lusakasa, 

What do you think of the idea, showing the tab status in the list?

For example, if a tab is pinned, then maybe add a small pin icon next to its entry on the list?

I am a heavy user of pinned versus non-pinned tabs and helping me distinguish those would be great.

Your input is much appreciated. 

Yours

**Comment by pureooze** [comment]
Hi @orschiro what would be the benefit (which modes and why) of being able to distinguish the pinned tabs from non pinned tabs?

I'm not sure what would be useful about seeing if a tab is pinned or not, to me it doesnt matter when you want to switch to it.

**Comment by orschiro** [comment]
@pureooze excellent remark. 8 days ago, when I submitted it initially, I had a concrete use case in mind.

For example, you may have the same website opened in several tabs, one of them pinned because it has special meaning to you. 

In that case, it would be useful being able to identify that tab based on its pinned status. 

But I agree, that may not be that much necessary. 

At the moment, I stopped using pinned tabs at all and thus the need for this request has vanished. 

Shall we close this issue thus?

Yours

**Comment by pureooze** [comment]
Sounds good, closing. We can reopen if there is a need in the future 😃

**Comment by orschiro** [comment]
Yes, thanks! :-)
