### ISSUE TITLE
Why does this require read/write data when Quick Tabs doesn't?

### ISSUE THREAD

**Issue by bumpysounds** [lusakasa/saka#94]
I really like the UI on this one, but I'm cautious about extensions that require this permission other than a couple that I trust. It would be cool to see how it can be removed.

**Comment by pureooze** [comment]
Saka lets you modify its behavior on the options page and needs to be able to read/write from storage in order to read/update the settings. I tried out Quick Tabs and it seems this extension doesn't have any modifiable settings so that would explain why it doesn't need to read/write.

**Comment by bumpysounds** [comment]
Bummer
