### ISSUE TITLE
Dangerous roadmap: you are overcomplicating extension

### ISSUE THREAD

**Issue by Yodzorah** [lusakasa/saka#99]
I've looked into the Features Roadmap at [saka.io](https://saka.io) and found it very concerning that you intend to implement the next features:

- Calculator
- Dictionary
- Show time

One guy at the Firefox store said one of the reasons this extension is so good is because it does _one_ thing _good_, in the true unix way, and I wholeheartedly agree. What you intend to do does not belong here. If a user _needs_ calculator or dictionary or time here, he's set up his environment _wrong_. It will not do to indulge users trying to compensate their lack of understanding the structure of things with over-designing, especially at the expense of the product's quality. Moreover, the first two features cannot be properly implemented in this extension without moving its focus away from browsing, and poor implementations of them will not make any sense; the third feature is pure joke considering the fact that most users (no matter the OS they use) either have default panel with clock and whatnot or don't need it at all. You will only create unneeded code and take unneeded space and requests for something useless.

I gave up on Vivaldi because of the _exact_ same approach. When I've first heard about them implementing calculator (!) in a browser, I couldn't believe I _believed_ in those devs. Please, don't spoil your _awesome_ extension only because you feel powerful when implementing _something_. Or at least split the extension in two and release the "Calculator Included!" version as a separate extension.

Also, FYI: [suckless.org](https://suckless.org/philosophy/).

---
Standard notice: I hope you won't take my honesty as being malicious. I seek only improvement, not hurt feelings.

**Comment by pureooze** [comment]
>this extension is so good is because it does one thing good, in the true unix way
I would argue that Saka does not do just "one thing".

Regardless, the website is quite old and hasnt been updated in a while. There are no plans to add a calculator/dictionary/showing time.
